use_frameworks!

platform :ios, '8.0'

target 'GalleryDemo' do
 pod 'Gallery', path: '../../'
 pod 'Lightbox', git: 'https://github.com/hyperoslo/Lightbox.git', branch: 'swift-3'
 pod 'Sugar', git: 'https://github.com/hyperoslo/Sugar.git', branch: 'master'
 pod 'Hue', git: 'https://github.com/hyperoslo/Hue.git', branch: 'master'
end

